name: Build and Push Microservices

on:
  push:
    branches: [ "main" ]
    # Only trigger when code in these directories changes
    paths:
      - 'apps/**'
      - 'frontend/**'
      - '.github/workflows/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      # This runs all 3 builds at the same time!
      matrix:
        include:
          - service_name: auth-service
            context: .
            dockerfile: apps/auth-service/Dockerfile
            image_name: hasib-auth
          - service_name: user-service
            context: .
            dockerfile: apps/user-service/Dockerfile
            image_name: hasib-user
          - service_name: frontend
            context: ./frontend
            dockerfile: frontend/Dockerfile
            image_name: hasib-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          # We tag it with 'latest' and the short Git commit SHA for versioning
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.image_name }}:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.image_name }}:${{ github.sha }}
          # Inject Build Args for the Frontend
          build-args: |
            VITE_AUTH_SERVICE_URL=${{ secrets.VITE_AUTH_SERVICE_URL }}
            VITE_USER_SERVICE_URL=${{ secrets.VITE_USER_SERVICE_URL }}